superstore:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: my_user
      pass: my_password
      dbname: superstore
      schema: staging
